### ISSUE TITLE
It‘s a compliment.

### ISSUE THREAD

**Issue by TwiceTry** [SykieChen/BJUT_Always_Online#8]
之前没有在github搜，我就开始写了，也是python，也是多账号轮换，也是有个单次流量，单次时长，还有一个停止流量。
我的是：

> - ini 存储 上述值
> - main.py 主程序
> - Useragent.py 生成随机浏览器标识

**最近遇到个问题：**lgn.bjut.edu.cn 这个网络下，多次访问 设备mac地址会被网络禁，导致程序只能在bjut_wifi下用，我把程序放在openwrt 运行的。
使用端口扫描工具大范围扫描校园网 也会被禁。
等闲下来我再好好修改吧，在此致敬了。

**Comment by tojo17** [comment]
我已经毕业好几年了，不了解现在学校的情况。访问网关查询当前流量会被封禁？很奇怪的策略。
另外你用扫描器被封当然是正常的，这种攻击行为是触犯法律的。
如果有什么修改想要合并的话，可以测试之后提交PR进来。
祝好。
